window.PlantrichTranslations = window.PlantrichTranslations || {};
window.PlantrichTranslations.de = window.PlantrichTranslations.de || {};

window.PlantrichTranslations.de.agbContent = `
  <p class="legal-document__company">Plantrich GmbH, Am Südermoor 30, 24888 Steinfeld</p>

  <section>
    <h2>§ 1 Geltung</h2>
    <p>(1) Diese Verkaufs- und Lieferbedingungen gelten ausschließlich und nur gegenüber Unternehmen, juristischen Personen des öffentlichen Rechts oder öffentlich-Rechtlichen Sondervermögen von § 310 Absatz 1 BGB. Alle Lieferungen, Leistungen und Angebote von Plantrich erfolgen ausschließlich aufgrund dieser Verkaufs- und Lieferbedingungen. Diese sind Bestandteil aller Verträge, die Plantrich mit seinen Vertragspartnern (nachfolgend auch “Käufer” oder “Auftraggeber” genannt) über die von Plantrich angebotenen Lieferungen oder Leistungen schließt. Sie gelten auch für alle zukünftigen Lieferungen, Leistungen oder Angebote an den Auftraggeber, selbst wenn sie nicht nochmals gesondert vereinbart werden.</p>
    <p>(2) Geschäftsbedingungen des Auftraggebers oder Dritter finden keine Anwendung, auch wenn Plantrich ihrer Geltung im Einzelfall nicht gesondert widerspricht. Selbst wenn Plantrich auf ein Schreiben Bezug nimmt, das Geschäftsbedingungen des Auftraggebers oder eines Dritten enthält oder auf solche verweist, liegt darin kein Einverständnis mit der Geltung jener Geschäftsbedingungen.</p>
  </section>

  <section>
    <h2>§ 2 Angebot und Vertragsabschluss</h2>
    <p>(1) Alle Angebote von Plantrich sind freibleibend. Auf Abschluss oder Änderung von Verträgen gerichtete Erklärungen werden erst durch eine schriftliche Auftragsbestätigung von Plantrich verbindlich.</p>
    <p>(2) Allein maßgeblich für die Rechtsbeziehungen zwischen Plantrich und dem Auftraggeber ist der schriftlich geschlossene Vertrag, einschließlich dieser Allgemeinen Verkaufs- und Lieferbedingungen. Dieser gibt alle Abreden zwischen den Vertragsparteien zum Vertragsgegenstand vollständig wider. Alle Informationen (z.B. Produktbeschreibungen und Preisangaben) auf unserer Website, in Prospekten sowie anderen Werbemitteln über die von uns angebotenen Waren sind unverbindlich.</p>
    <p>(3) Ergänzungen und Abänderungen der getroffenen Vereinbarungen einschließlich dieser Allgemeinen Verkaufs- und Lieferbedingungen bedürfen zu ihrer Wirksamkeit der Schriftform. Zur Wahrung der Schriftform genügt die Übermittlung per Telefax oder per Email.</p>
    <p>(4) Angaben von Plantrich zum Gegenstand der Lieferung oder Leistung (zB. Gewichte, Maße, Gebrauchswerte, Belastbarkeit, Toleranzen und technische Daten) sowie unsere Darstellungen desselben (zB. Zeichnungen und Abbildungen) sind nur annähernd maßgeblich, soweit nicht die Verwendbarkeit zum vertraglich vorgesehenen Zweck eine genaue Übereinstimmung voraussetzt. Sie sind keine garantierten Beschaffenheitsmerkmale, sondern Beschreibungen oder Kennzeichnungen der Lieferung oder Leistung. Handelsübliche Abweichungen und Abweichungen, die aufgrund rechtlicher Vorschriften erfolgen oder technische Verbesserungen darstellen, sowie die Ersetzung von Bauteilen durch gleichwertige Teile sind zulässig, soweit sie die Verwendbarkeit zum vertraglich vorgesehenen Zweck nicht beeinträchtigen. Gleiches gilt für geringfügige Farbabweichungen.</p>
    <p>(5) Plantrich behält sich das Eigentum oder Urheberrecht an allen von ihm abgegebenen Angeboten und Kostenvoranschlägen sowie dem Auftraggeber zur Verfügung gestellten Zeichnungen, Abbildungen, Berechnungen, Prospekten, Katalogen, Modellen, Werkzeugen und anderen Unterlagen und Hilfsmitteln vor. Der Auftraggeber darf diese Gegenstände ohne ausdrückliche Zustimmung von Plantrich weder als solche noch inhaltlich Dritten zugänglich machen, sie bekannt geben, selbst oder durch Dritte nutzen oder vervielfältigen. Er hat auf Verlangen von Plantrich diese Gegenstände vollständig an diesen zurückzugeben und eventuell gefertigte Kopien zu vernichten, wenn sie von ihm im ordnungsgemäßen Geschäftsgang nicht mehr benötigt werden oder wenn Verhandlungen nicht zum Abschluss eines Vertrages führen.</p>
  </section>

  <section>
    <h2>§ 3 Preise und Zahlung</h2>
    <p>(1) Die Preise gelten für den in den Auftragsbestätigungen aufgeführten Leistungs- und Lieferungsumfang. Mehr- oder Sonderleistungen werden gesondert berechnet. Die Preise verstehen sich in EURO ab Werk zuzüglich Verpackung, der gesetzlichen Mehrwertsteuer, bei Exportlieferungen Zoll sowie Gebühren und anderer öffentlicher Abgaben.</p>
    <p>(2) Sofern nichts anderes vereinbart ist, gelten die bei Vertragsabschluss gültigen Preise. Ändern sich später als zwei Monate nach Vertragsschluss Abgaben oder andere Fremdkosten, die im vereinbarten Preis enthalten sind, ist Plantrich im entsprechenden Umfang zu einer Preisänderung berechtigt.</p>
    <p>(3) Rechnungsbeträge sind innerhalb von 10 Tagen nach Lieferung und Rechnungsstellung ohne jeden Abzug zu bezahlen, sofern nicht etwas anderes schriftlich vereinbart ist. Maßgebend für das Datum der Zahlung ist der Eingang bei Plantrich. Schecks gelten erst nach Einlösung als Zahlung. Leistet der Auftraggeber bei Fälligkeit nicht, so sind die ausstehenden Beträge ab dem Tag der Fälligkeit mit 9 Prozentpunkten über dem jeweiligen Basiszinssatz p. a. zu verzinsen; die Geltendmachung höherer Zinsen und weiterer Schäden im Falle des Verzugs bleibt unberührt.</p>
    <p>(4) Die Aufrechnung mit Gegenansprüchen des Auftraggebers ist nur zulässig, soweit die Gegenansprüche unbestritten oder rechtskräftig festgestellt sind. Ein Zurückbehaltungsrecht durch den Auftraggeber ist ausgeschlossen.</p>
    <p>(5) Plantrich ist berechtigt, noch ausstehende Lieferungen oder Leistungen nur gegen Vorauszahlung oder Sicherheitsleistung auszuführen oder zu erbringen, wenn Plantrich nach Abschluss des Vertrages Umstände bekannt werden, welche die Kreditwürdigkeit des Auftraggebers wesentlich zu mindern geeignet sind und durch welche die Bezahlung der offenen Forderungen von Plantrich durch den Auftraggeber aus dem jeweiligen Vertragsverhältnis (einschließlich aus anderen Einzelaufträgen, für die derselbe Rahmenvertrag gilt) gefährdet wird.</p>
  </section>

  <section>
    <h2>§ 4 Lieferung und Lieferzeit</h2>
    <p>(1) Lieferungen erfolgen ab Werk.</p>
    <p>(2) Von Plantrich in Aussicht gestellte Fristen und Termine für Lieferungen und Leistungen gelten stets nur annähernd, es sei denn, dass ausdrücklich eine feste Frist oder ein fester Termin zugesagt oder vereinbart ist. Sofern Versendung vereinbart wurde, beziehen sich Lieferfristen und Liefertermine auf den Zeitpunkt der Übergabe an den Spediteur, Frachtführer oder sonst mit dem Transport beauftragten Dritten.</p>
    <p>(3) Plantrich kann – unbeschadet der Rechte aus Verzug des Auftraggebers –vom Auftraggeber eine Verlängerung von Liefer- und Leistungsfristen oder eine Verschiebung von Liefer- und Leistungsterminen um den Zeitraum verlangen, in dem der Auftraggeber seinen vertraglichen Verpflichtungen Plantrich gegenüber nicht nachkommt.</p>
    <p>(4) Plantrich haftet nicht für Unmöglichkeit der Lieferung oder für Lieferverzögerungen, soweit diese durch höhere Gewalt oder sonstige, zum Zeitpunkt des Vertragsabschlusses nicht vorhersehbare Ereignisse (zB. Betriebsstörungen aller Art, Schwierigkeiten in der Material- oder Energiebeschaffung, Transportverzögerungen, Streiks, rechtmäßige Aussperrungen, Mangel an Arbeitskräften, Energie oder Rohstoffen, Schwierigkeiten bei der Beschaffung von notwendigen behördlichen Genehmigungen, behördliche Maßnahmen oder die ausbleibende, nicht richtige oder nicht rechtzeitige Belieferung durch Lieferanten ) verursacht worden sind, die Plantrich nicht zu vertreten hat. Sofern solche Ereignisse Plantrich die Lieferung oder Leistung wesentlich erschweren oder unmöglich machen und die Behinderung nicht nur von vorübergehender Dauer ist, ist Plantrich zum Rücktritt vom Vertrag berechtigt. Bei Hindernissen vorübergehender Dauer verlängern sich die Liefer- oder Leistungsfristen oder verschieben sich die Liefer- oder Leistungstermine um den Zeitraum der Behinderung zuzüglich einer angemessenen Anlauffrist. Soweit dem Auftraggeber infolge der Verzögerung die Abnahme der Lieferung oder Leistung nicht zuzumuten ist, kann er durch unverzügliche schriftliche Erklärung gegenüber Plantrich vom Vertrag zurücktreten.</p>
    <p>(5) Plantrich ist nur zu Teillieferungen berechtigt, wenn</p>
    <ul>
      <li>die Teillieferung für den Auftraggeber im Rahmen des vertraglichen Bestimmungszwecks verwendbar ist,</li>
      <li>die Lieferung der restlichen bestellten Ware sichergestellt ist und</li>
      <li>dem Auftraggeber hierdurch kein erheblicher Mehraufwand oder zusätzliche Kosten entstehen (es sei denn, Plantrich erklärt sich zur Übernahme dieser Kosten bereit).</li>
    </ul>
    <p>(6) Gerät Plantrich mit einer Lieferung oder Leistung in Verzug oder wird ihm eine Lieferung oder Leistung, gleich aus welchem Grunde, unmöglich, so ist die Haftung von Plantrich auf Schadensersatz nach Maßgabe des § 8 dieser Allgemeinen Lieferbedingungen beschränkt.</p>
  </section>

  <section>
    <h2>§ 5 Erfüllungsort, Versand, Verpackung, Gefahrübergang, Abnahme</h2>
    <p>(1) Erfüllungsort für alle Verpflichtungen aus dem Vertragsverhältnis ist der Geschäftssitz unseres Unternehmens in Steinfeld, soweit nichts anderes bestimmt ist.</p>
    <p>(2) Die Versandart und die Verpackung unterstehen dem pflichtgemäßen Ermessen von Plantrich.</p>
    <p>(3) Die Gefahr geht spätestens mit der Übergabe des Liefergegenstandes (wobei der Beginn des Verladevorgangs maßgeblich ist) an den Spediteur, Frachtführer oder sonst zur Ausführung der Versendung bestimmten Dritten auf den Auftraggeber über. Dies gilt auch dann, wenn Teillieferungen erfolgen oder Plantrich noch andere Leistungen (zB. Versand oder Installation) übernommen hat. Verzögert sich der Versand oder die Übergabe infolge eines Umstandes, dessen Ursache beim Auftraggeber liegt, geht die Gefahr von dem Tag an auf den Auftraggeber über, an dem der Liefergegenstand versandbereit ist und Plantrich dies dem Auftraggeber angezeigt hat.</p>
    <p>(4) Lagerkosten nach Gefahrübergang trägt der Auftraggeber. Bei Lagerung durch Plantrich betragen die Lagerkosten 0,25% des Rechnungsbetrages der zu lagernden Liefergegenstände pro abgelaufene Woche. Die Geltendmachung und der Nachweis weiterer oder geringerer Lagerkosten bleiben vorbehalten.</p>
    <p>(5) Die Sendung wird von Plantrich nur auf ausdrücklichen Wunsch des Auftraggebers und auf seine Kosten gegen Diebstahl, Bruch-, Transport-, Feuer- und Wasserschäden oder sonstige versicherbare Risiken versichert.</p>
    <p>(6) Soweit eine Abnahme stattzufinden hat, gilt die Kaufsache als abgenommen, wenn</p>
    <ul>
      <li>die Lieferung und, sofern Plantrich auch die Installation schuldet, die Installation abgeschlossen ist,</li>
      <li>Plantrich dies dem Auftraggeber unter Hinweis auf die Abnahmefiktion nach diesem § 5 (6) mitgeteilt und ihn zur Abnahme aufgefordert hat,</li>
      <li>seit der Lieferung oder Installation sechs Werktage vergangen sind oder der Auftraggeber mit der Nutzung der Kaufsache begonnen hat (zB. die gelieferte Anlage in Betrieb genommen hat), und</li>
      <li>der Auftraggeber die Abnahme innerhalb dieses Zeitraums aus einem anderen Grund als wegen eines von Plantrich angezeigten Mangels, der die Nutzung der Kaufsache unmöglich macht oder wesentlich beeinträchtigt, unterlassen hat.</li>
    </ul>
  </section>

  <section>
    <h2>§ 6 Gewährleistung, Sachmängel</h2>
    <p>(1) Die Gewährleistungsfrist beträgt ein Jahr ab Lieferung oder, soweit eine Abnahme erforderlich ist, ab der Abnahme.</p>
    <p>(2) Die gelieferten Gegenstände sind unverzüglich nach Ablieferung an den Auftraggeber oder an den von ihm bestimmten Dritten sorgfältig zu untersuchen. Sie gelten als genehmigt, wenn Plantrich nicht eine schriftliche Mängelrüge hinsichtlich offensichtlicher Mängel oder anderer Mängel, die bei einer unverzüglichen, sorgfältigen Untersuchung erkennbar waren, unverzüglich nach Ablieferung des Liefergegenstandes oder ansonsten unverzüglich nach der Entdeckung des Mangels oder jedem früheren Zeitpunkt, in dem der Mangel für den Auftraggeber bei normaler Verwendung des Liefergegenstandes ohne nähere Untersuchung erkennbar war, in der in § 2 (2) Satz 6 bestimmten Weise zugegangen ist. Auf Verlangen von Plantrich ist der beanstandete Liefergegenstand frachtfrei an Plantrich zurückzusenden. Bei berechtigter Mängelrüge vergütet Plantrich die Kosten des günstigsten Versandweges; dies gilt nicht, soweit die Kosten sich erhöhen, weil der Liefergegenstand sich an einem anderen Ort als dem Ort des bestimmungsgemäßen Gebrauchs befindet.</p>
    <p>(3) Bei Sachmängeln der gelieferten Gegenstände ist Plantrich nach seiner innerhalb angemessener Frist zu treffenden Wahl zunächst zur Nachbesserung oder Ersatzlieferung verpflichtet und berechtigt. Im Falle des Fehlschlagens, d.h. der Unmöglichkeit, Unzumutbarkeit, Verweigerung oder unangemessenen Verzögerung der Nachbesserung oder Ersatzlieferung, kann der Auftraggeber vom Vertrag zurücktreten oder den Kaufpreis angemessen mindern.</p>
    <p>(4) Beruht ein Mangel auf dem Verschulden von Plantrich, kann der Auftraggeber unter den in § 8 bestimmten Voraussetzungen Schadensersatz verlangen.</p>
    <p>(5) Bei Mängeln von Bauteilen anderer Hersteller, die Plantrich aus lizenzrechtlichen oder tatsächlichen Gründen nicht beseitigen kann, wird Plantrich nach seiner Wahl seine Gewährleistungsansprüche gegen die Hersteller und Lieferanten für Rechnung des Auftraggebers geltend machen oder an den Auftraggeber abtreten. Gewährleistungsansprüche gegen Plantrich bestehen bei derartigen Mängeln unter den sonstigen Voraussetzungen und nach Maßgabe dieser Allgemeinen Verkaufs- und Lieferbedingungen nur, wenn die gerichtliche Durchsetzung der vorstehend genannten Ansprüche gegen den Hersteller und Lieferanten erfolglos war oder, beispielsweise aufgrund einer Insolvenz, aussichtslos ist. Während der Dauer des Rechtsstreits ist die Verjährung der betreffenden Gewährleistungsansprüche des Auftraggebers gegen Plantrich gehemmt.</p>
    <p>(6) Die Gewährleistung entfällt, wenn der Auftraggeber ohne Zustimmung von Plantrich den Liefergegenstand ändert oder durch Dritte ändern lässt und die Mängelbeseitigung hierdurch unmöglich oder unzumutbar erschwert wird. In jedem Fall hat der Auftraggeber die durch die Änderung entstehenden Mehrkosten der Mängelbeseitigung zu tragen.</p>
    <p>(7) Eine im Einzelfall mit dem Auftraggeber vereinbarte Lieferung gebrauchter Gegenstände erfolgt unter Ausschluss jeglicher Gewährleistung für Sachmängel.</p>
    <p>(8) Mängelansprüche bestehen nicht bei nur unerheblicher Abweichung von der vereinbarten Beschaffenheit, bei nur unerheblicher Beeinträchtigung der Brauchbarkeit, bei natürlicher Abnutzung oder Verschleiß wie bei Schäden, die nach dem Gefahrenübergang infolge fehlerhafter oder nachlässiger Behandlung oder übermäßiger Beanspruchung entstehen.</p>
  </section>

  <section>
    <h2>§ 7 Schutzrechte, Freistellung von Rechten Dritter</h2>
    <p>(1) Plantrich steht nach Maßgabe dieses § 7 dafür ein, dass der Liefergegenstand frei von gewerblichen Schutzrechten oder Urheberrechten Dritter ist. Jeder Vertragspartner wird den anderen Vertragspartner unverzüglich schriftlich benachrichtigen, falls ihm gegenüber Ansprüche wegen der Verletzung solcher Rechte geltend gemacht werden.</p>
    <p>(2) In dem Fall, dass der Liefergegenstand ein gewerbliches Schutzrecht oder Urheberrecht eines Dritten verletzt, wird Plantrich nach seiner Wahl und auf seine Kosten den Liefergegenstand derart abändern oder austauschen, dass keine Rechte Dritter mehr verletzt werden, der Liefergegenstand aber weiterhin die vertraglich vereinbarten Funktionen erfüllt, oder dem Auftraggeber durch Abschluss eines Lizenzvertrages das Nutzungsrecht verschaffen. Gelingt Plantrich dies innerhalb eines angemessenen Zeitraums nicht, ist der Auftraggeber berechtigt, von dem Vertrag zurückzutreten oder den Kaufpreis angemessen zu mindern. Etwaige Schadensersatzansprüche des Auftraggebers unterliegen den Beschränkungen des § 8 dieser Allgemeinen Verkaufs- und Lieferbedingungen.</p>
    <p>(3) Bei Rechtsverletzungen durch von Plantrich gelieferte Produkte anderer Hersteller wird Plantrich nach seiner Wahl seine Ansprüche gegen die Hersteller und Vorlieferanten für Rechnung des Auftraggebers geltend machen oder an den Auftraggeber abtreten. Ansprüche gegen Plantrich bestehen in diesen Fällen nach Maßgabe dieses § 7 nur, wenn die gerichtliche Durchsetzung der vorstehend genannten Ansprüche gegen die Hersteller und Vorlieferanten erfolglos war oder, beispielsweise aufgrund einer Insolvenz, aussichtslos ist.</p>
    <p>(4) Soweit Plantrich nach Vorgaben des Auftraggebers Produkte gestaltet oder in Produktion gibt, haftet der Auftraggeber dafür, dass das nach den Vorgaben des Auftraggebers erstellte Produkt Rechte Dritter (z.B. Markenrechte, Patente, Urheberrechte) nicht verletzt. Insoweit stellt der Auftraggeber Plantrich von allen Ansprüchen frei, die Dritte aus einer diesbezüglichen Rechtsverletzung geltend machen.</p>
  </section>

  <section>
    <h2>§ 8 Haftung auf Schadensersatz wegen Verschuldens</h2>
    <p>(1) Die Haftung von Plantrich auf Schadensersatz, gleich aus welchem Rechtsgrund, insbesondere aus Unmöglichkeit, Verzug, mangelhafter oder falscher Lieferung, Vertragsverletzung, Verletzung von Pflichten bei Vertragsverhandlungen und unerlaubter Handlung ist, soweit es dabei jeweils auf ein Verschulden ankommt, nach Maßgabe dieses § 8 eingeschränkt.</p>
    <p>(2) Plantrich haftet nicht im Falle einfacher Fahrlässigkeit seiner Organe, gesetzlichen Vertreter, Angestellten oder sonstigen Erfüllungsgehilfen soweit es sich nicht um eine Verletzung vertragswesentlicher Pflichten handelt. Vertragswesentlich sind die Verpflichtung zur rechtzeitigen Lieferung und Installation des von wesentlichen Mängeln freien Liefergegenstands sowie Beratungs-, Schutz- und Obhutspflichten, die dem Auftraggeber die vertragsgemäße Verwendung des Liefergegenstands ermöglichen sollen oder den Schutz von Leib oder Leben von Personal des Auftraggebers oder den Schutz von dessen Eigentum vor erheblichen Schäden bezwecken.</p>
    <p>(3) Soweit Plantrich gemäß § 8 (2) dem Grunde nach auf Schadensersatz haftet, ist diese Haftung auf Schäden begrenzt, die Plantrich bei Vertragsschluss als mögliche Folge einer Vertragsverletzung vorausgesehen hat oder die Plantrich bei Anwendung verkehrsüblicher Sorgfalt hätte voraussehen müssen. Mittelbare Schäden und Folgeschäden, die Folge von Mängeln des Liefergegenstands sind, sind außerdem nur ersatzfähig, soweit solche Schäden bei bestimmungsgemäßer Verwendung des Liefergegenstands typischerweise zu erwarten sind.</p>
    <p>(4) Im Falle einer Haftung für einfache Fahrlässigkeit ist die Ersatzpflicht von Plantrich für Sachschäden auf 1,5 Mio. EUR je Schadensfall beschränkt, auch wenn es sich um eine Verletzung vertragswesentlicher Pflichten handelt. Im Falle einer Haftung für einfache Fahrlässigkeit ist die Ersatzpflicht von Plantrich für Vermögensschäden auf 150.000,00 EUR je Schadensfall beschränkt, auch wenn es sich um eine Verletzung vertragswesentlicher Pflichten handelt.</p>
    <p>(5) Die vorstehenden Haftungsausschlüsse und -beschränkungen gelten in gleichem Umfang zugunsten der Organe, gesetzlichen Vertreter, Angestellten und sonstigen Erfüllungsgehilfen von Plantrich.</p>
    <p>(6) Soweit Plantrich technische Auskünfte gibt oder beratend tätig wird und diese Auskünfte oder Beratung nicht zu dem von Plantrich geschuldeten, vertraglich vereinbarten Leistungsumfang gehören, geschieht dies unentgeltlich und unter Ausschluss jeglicher Haftung.</p>
    <p>(7) Die Einschränkungen dieses § 8 gelten nicht für die Haftung von Plantrich wegen vorsätzlichen Verhaltens, für garantierte Beschaffenheitsmerkmale, wegen Verletzung des Lebens, des Körpers oder der Gesundheit oder nach dem Produkthaftungsgesetz.</p>
  </section>

  <section>
    <h2>§ 9 Eigentumsvorbehalt</h2>
    <p>(1) Der nachfolgend vereinbarte Eigentumsvorbehalt dient der Sicherung aller jeweils bestehenden derzeitigen und künftigen Forderungen von Plantrich gegen den Auftraggeber aus der zwischen den Vertragspartnern bestehenden Lieferbeziehung.</p>
    <p>(2) Die von Plantrich an den Käufer gelieferte Ware bleibt bis zur vollständigen Bezahlung aller gesicherten Forderungen Eigentum von Plantrich. Die Ware sowie die nach dieser Klausel an ihre Stelle tretende, vom Eigentumsvorbehalt erfasste Ware wird nachfolgend Vorbehaltsware genannt.</p>
    <p>(3) Der Käufer verwahrt die Vorbehaltsware unentgeltlich für Plantrich.</p>
    <p>(4) Der Käufer ist berechtigt, die Vorbehaltsware bis zum Eintritt des Verwertungsfalls (Absatz 9) im ordnungsgemäßen Geschäftsverkehr zu verarbeiten und zu veräußern. Verpfändungen und Sicherungsübereignungen sind unzulässig.</p>
    <p>(5) Wird die Vorbehaltsware vom Käufer verarbeitet, so wird vereinbart, dass die Verarbeitung im Namen und für Rechnung von Plantrich als Hersteller erfolgt und Plantrich unmittelbar das Eigentum oder – wenn die Verarbeitung aus Stoffen mehrerer Eigentümer erfolgt oder der Wert der verarbeiteten Sache höher ist als der Wert der Vorbehaltsware – das Miteigentum (Bruchteilseigentum) an der neu geschaffenen Sache im Verhältnis des Werts der Vorbehaltsware zum Wert der neu geschaffenen Sache erwirbt. Für den Fall, dass kein solcher Eigentumserwerb bei Plantrich eintreten sollte, überträgt der Käufer bereits jetzt sein künftiges Eigentum oder – im og. Verhältnis – Miteigentum an der neu geschaffenen Sache zur Sicherheit an Plantrich. Wird die Vorbehaltsware mit anderen Sachen zu einer einheitlichen Sache verbunden oder untrennbar vermischt und ist eine der anderen Sachen als Hauptsache anzusehen, so überträgt Plantrich, soweit die Hauptsache ihm gehört, dem Käufer anteilig das Miteigentum an der einheitlichen Sache in dem in Satz 1 genannten Verhältnis.</p>
    <p>(6) Im Fall der Weiterveräußerung der Vorbehaltsware tritt der Käufer bereits jetzt sicherungshalber die hieraus entstehende Forderung gegen den Erwerber – bei Miteigentum von Plantrich an der Vorbehaltsware anteilig entsprechend dem Miteigentumsanteil – an Plantrich ab. Gleiches gilt für sonstige Forderungen, die an die Stelle der Vorbehaltsware treten oder sonst hinsichtlich der Vorbehaltsware entstehen, wie z.B. Versicherungsansprüche oder Ansprüche aus unerlaubter Handlung bei Verlust oder Zerstörung. Plantrich ermächtigt den Käufer widerruflich, die an Plantrich abgetretenen Forderungen im eigenen Namen einzuziehen. Plantrich darf diese Einzugsermächtigung nur im Verwertungsfall widerrufen.</p>
    <p>(7) Greifen Dritte auf die Vorbehaltsware zu, insbesondere durch Pfändung, wird der Käufer sie unverzüglich auf das Eigentum von Plantrich hinweisen und Plantrich hierüber informieren, um Plantrich die Durchsetzung seiner Eigentumsrechte zu ermöglichen. Sofern der Dritte nicht in der Lage ist, Plantrich die in diesem Zusammenhang entstehenden gerichtlichen oder außergerichtlichen Kosten zu erstatten, haftet hierfür der Käufer an Plantrich.</p>
    <p>(8) Plantrich wird die Vorbehaltsware sowie die an ihre Stelle tretenden Sachen oder Forderungen auf Verlangen nach seiner Wahl freigeben, soweit ihr Wert die Höhe der gesicherten Forderungen um mehr als 35% übersteigt.</p>
    <p>(9) Tritt Plantrich bei vertragswidrigem Verhalten des Käufers – insbesondere Zahlungsverzug – vom Vertrag zurück (Verwertungsfall), ist Plantrich berechtigt, die Vorbehaltsware herauszuverlangen.</p>
  </section>

  <section>
    <h2>§ 10 Schlussbestimmungen</h2>
    <p>(1) Gerichtsstand für alle etwaigen Streitigkeiten aus der Geschäftsbeziehung zwischen Plantrich und dem Auftraggeber ist der Sitz von Plantrich. Zwingende gesetzliche Bestimmungen über ausschließliche Gerichtsstände bleiben von dieser Regelung unberührt.</p>
    <p>(2) Die Beziehungen zwischen Plantrich und dem Auftraggeber unterliegen ausschließlich dem Recht der Bundesrepublik Deutschland. Das Übereinkommen der Vereinten Nationen über Verträge über den internationalen Warenkauf vom 11. April 1980 (CISG) gilt nicht.</p>
    <p>(3) Soweit der Vertrag oder diese Allgemeinen Verkaufs- und Lieferbedingungen Regelungslücken enthalten, gelten zur Ausfüllung dieser Lücken diejenigen rechtlich wirksamen Regelungen als vereinbart, welche die Vertragspartner nach den wirtschaftlichen Zielsetzungen des Vertrages und dem Zweck dieser Allgemeinen Verkaufs- und Lieferbedingungen vereinbart hätten, wenn sie die Regelungslücke gekannt hätten.</p>
  </section>

  <section>
    <h2>Hinweis</h2>
    <p>Der Auftraggeber nimmt davon Kenntnis, dass Plantrich personenbezogene Daten aus dem Vertragsverhältnis gemäß Art. 6 Abs. 1 lit. b und lit. f DSGVO zum Zwecke der Vertragsdurchführung sowie zur Wahrung berechtigter Interessen verarbeitet und speichert. Eine Weitergabe an Dritte erfolgt ausschließlich, soweit dies zur Vertragserfüllung erforderlich ist (z.B. an Versanddienstleister, Kreditinstitute, Versicherungen) oder eine gesetzliche Verpflichtung besteht. Die Daten werden für die Dauer der gesetzlichen Aufbewahrungsfristen gespeichert. Dem Auftraggeber stehen die Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch sowie ein Beschwerderecht bei einer Aufsichtsbehörde zu. Weitere Informationen zur Datenverarbeitung enthält unsere <a href="privacy.html">Datenschutzerklärung</a>.</p>
    <p class="legal-document__date">Stand 14.09.2026</p>
  </section>

  <section>
    <h2>Alternative Streitbeilegung gemäß Art. 14 Abs. 1 ODR-VO und § 36 VSBG</h2>
    <p>Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit, die du unter <a href="https://ec.europa.eu/consumers/odr">https://ec.europa.eu/consumers/odr</a> findest. Zur Teilnahme an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle sind wir nicht verpflichtet und nicht bereit.</p>
  </section>
`;
